apiVersion: kailas.cloud/v1
kind: Valkey
metadata:
  name: valkey-cluster
spec:
  # 3 primary nodes (shards)
  nodes: 3
  # No replicas for now (production would use replicas: 1)
  replicas: 0

  # Official valkey-bundle image with modules
  image: valkey/valkey-bundle:9.0.0-alpine

  # Load valkey-search module with coordinator enabled for cluster mode
  modules:
    - path: /usr/lib/valkey/libsearch.so
      args:
        - --use-coordinator
        - --reader-threads
        - "8"
        - --writer-threads
        - "4"
        - --hnsw-block-size
        - "10000"
        - --log-level
        - notice

  # Resource requests/limits
  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 2000m
      memory: 12Gi

  # Persistent storage using Hetzner Cloud Volumes
  storage:
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: hcloud-volumes
      resources:
        requests:
          storage: 100Gi

  # Security settings
  anonymousAuth: false
  volumePermissions: true

  # No TLS for internal cluster (add later if needed)
  tls: false

  # Monitoring
  prometheus: true
  serviceMonitor: true
