apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: llm
spec:
  serviceName: "ollama"
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        workload: ollama
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "ollama"
          effect: "NoSchedule"
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
              name: http
          readinessProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 25
            periodSeconds: 10
            failureThreshold: 6
          volumeMounts:
            - name: ollama-storage
              mountPath: /root/.ollama
          resources:
            requests:
              memory: "24Gi"
              cpu: "4"
            limits:
              memory: "28Gi"
              cpu: "8"
  volumeClaimTemplates:
    - metadata:
        name: ollama-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
