apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weaviate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://weaviate.github.io/weaviate-helm
    chart: weaviate
    targetRevision: 17.7.0
    helm:
      values: |
        replicas: 3
        storage:
          size: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: memory
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
